{
  "openapi": "3.1.0",
  "info": {
    "title": "CargoConnect Admin API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:5555",
      "description": "Local server"
    },
    {
      "url": "https://api.mycargoconnects.com",
      "description": "Live server"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "tags": [
    {
      "name": "---- Admin ----"
    },
    {
      "name": "Auth"
    },
    {
      "name": "Profile"
    },
    {
      "name": "Manage User"
    },
    {
      "name": "Manage Carrier"
    },
    {
      "name": "Service"
    },
    {
      "name": "Operator"
    },
    {
      "name": "Vehicle"
    },
    {
      "name": "Activity"
    },
    {
      "name": "Banners"
    },
    {
      "name": "TransitInfo"
    },
    {
      "name": "---- Common ----"
    },
    {
      "name": "Otp"
    },
    {
      "name": "Forgot Password"
    }
  ],
  "paths": {
    "/v1/admin/auth/logIn": {
      "post": {
        "tags": ["Auth"],
        "summary": "Log In",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "admin@gmail.com",
                  "password": "P@ssw0rd123"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/auth/token": {
      "post": {
        "tags": ["Auth"],
        "summary": "Refresh Token",
        "description": "This endpoint is used to refresh an expired access token using a valid refresh token.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/profile": {
      "get": {
        "tags": ["Profile"],
        "summary": "Fetch Profile",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/module/user": {
      "post": {
        "tags": ["Manage User"],
        "summary": "Create",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "companyName": {
                    "type": "string",
                    "example": "Example Logistics Inc."
                  },
                  "contactName": {
                    "type": "string",
                    "example": "John Doe"
                  },
                  "countryCode": {
                    "type": "integer",
                    "example": "1"
                  },
                  "contactNumber": {
                    "type": "string",
                    "example": "1234567890"
                  },
                  "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "Password123"
                  },
                  "commercialReference[0][companyName]": {
                    "type": "string",
                    "example": "Commercial Partner 1"
                  },
                  "commercialReference[0][contactName]": {
                    "type": "string",
                    "example": "Jane Smith"
                  },
                  "commercialReference[0][emailAddress]": {
                    "type": "string",
                    "example": "jane.smith@partner1.com"
                  },
                  "commercialReference[0][countryCode]": {
                    "type": "integer",
                    "example": "1"
                  },
                  "commercialReference[0][contactNo]": {
                    "type": "integer",
                    "example": "9876543210"
                  },
                  "commercialReference[1][companyName]": {
                    "type": "string",
                    "example": "Commercial Partner 2"
                  },
                  "commercialReference[1][contactName]": {
                    "type": "string",
                    "example": "James Brown"
                  },
                  "commercialReference[1][emailAddress]": {
                    "type": "string",
                    "example": "james.brow0n@partner2.com"
                  },
                  "commercialReference[1][countryCode]": {
                    "type": "integer",
                    "example": "44"
                  },
                  "companyFormationType": {
                    "type": "string",
                    "example": "USA"
                  },
                  "commercialReference[1][contactNo]": {
                    "type": "integer",
                    "example": "447123456789"
                  },
                  "profilePicture": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_usa_w9_Form": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_usa_utility_Bill": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_copia_Rfc_Form": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_constance_Of_Fiscal_Situation": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_proof_of_Favorable": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_proof_Of_Address": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": ["Manage User"],
        "summary": "Get All",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "keyWord",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "unity"
          },
          {
            "name": "sortBy",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "blocked , recent , all"
          },
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "1"
          },
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "10"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/module/user/{userAccountId}": {
      "get": {
        "tags": ["Manage User"],
        "summary": "Get Details",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["Manage User"],
        "summary": "Update",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "companyName": {
                    "type": "string",
                    "example": "Example Logistics Inc."
                  },
                  "contactName": {
                    "type": "string",
                    "example": "John Doe"
                  },
                  "countryCode": {
                    "type": "integer",
                    "example": "1"
                  },
                  "contactNumber": {
                    "type": "string",
                    "example": "1234567890"
                  },
                  "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "Password123"
                  },
                  "commercialReference[0][companyName]": {
                    "type": "string",
                    "example": "Commercial Partner 1"
                  },
                  "commercialReference[0][contactName]": {
                    "type": "string",
                    "example": "Jane Smith"
                  },
                  "commercialReference[0][emailAddress]": {
                    "type": "string",
                    "example": "jane.smith@partner1.com"
                  },
                  "commercialReference[0][countryCode]": {
                    "type": "integer",
                    "example": "1"
                  },
                  "commercialReference[0][contactNo]": {
                    "type": "integer",
                    "example": "9876543210"
                  },
                  "commercialReference[1][companyName]": {
                    "type": "string",
                    "example": "Commercial Partner 2"
                  },
                  "commercialReference[1][contactName]": {
                    "type": "string",
                    "example": "James Brown"
                  },
                  "commercialReference[1][emailAddress]": {
                    "type": "string",
                    "example": "james.brown@partner2.com"
                  },
                  "commercialReference[1][countryCode]": {
                    "type": "integer",
                    "example": "44"
                  },
                  "companyFormationType": {
                    "type": "string",
                    "example": "USA"
                  },
                  "commercialReference[1][contactNo]": {
                    "type": "integer",
                    "example": "447123456789"
                  },
                  "profilePicture": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_usa_w9_Form": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_usa_utility_Bill": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_copia_Rfc_Form": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_constance_Of_Fiscal_Situation": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_proof_of_Favorable": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_proof_Of_Address": {
                    "type": "string",
                    "format": "binary"
                  },
                  "isBlocked": {
                    "type": "boolean",
                    "example": "false"
                  },
                  "verifyByAdmin": {
                    "type": "boolean",
                    "example": "true"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": ["Manage User"],
        "summary": "Delete",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/module/verify/user/{userAccountId}": {
      "post": {
        "tags": ["Manage User"],
        "summary": "Verify",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": ""
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/module/unverify/user/{userAccountId}": {
      "delete": {
        "tags": ["Manage User"],
        "summary": "Unverify",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/module/carrier": {
      "post": {
        "tags": ["Manage Carrier"],
        "summary": "Create",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "companyName": {
                    "type": "string",
                    "example": "Example Logistics Inc."
                  },
                  "contactName": {
                    "type": "string",
                    "example": "John Doe"
                  },
                  "countryCode": {
                    "type": "integer",
                    "example": "1"
                  },
                  "contactNumber": {
                    "type": "string",
                    "example": "1234567890"
                  },
                  "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "Password123"
                  },
                  "commercialReference[0][companyName]": {
                    "type": "string",
                    "example": "Commercial Partner 1"
                  },
                  "commercialReference[0][contactName]": {
                    "type": "string",
                    "example": "Jane Smith"
                  },
                  "commercialReference[0][emailAddress]": {
                    "type": "string",
                    "example": "jane.smith@partner1.com"
                  },
                  "commercialReference[0][countryCode]": {
                    "type": "integer",
                    "example": "1"
                  },
                  "commercialReference[0][contactNo]": {
                    "type": "integer",
                    "example": "9876543210"
                  },
                  "commercialReference[1][companyName]": {
                    "type": "string",
                    "example": "Commercial Partner 2"
                  },
                  "commercialReference[1][contactName]": {
                    "type": "string",
                    "example": "James Brown"
                  },
                  "commercialReference[1][emailAddress]": {
                    "type": "string",
                    "example": "james.brown@partner2.com"
                  },
                  "commercialReference[1][countryCode]": {
                    "type": "integer",
                    "example": "44"
                  },
                  "commercialReference[1][contactNo]": {
                    "type": "integer",
                    "example": "447123456789"
                  },
                  "companyFormationType": {
                    "type": "string",
                    "example": "USA"
                  },
                  "profilePicture": {
                    "type": "string",
                    "format": "binary"
                  },
                  "scac": {
                    "type": "string",
                    "format": "binary"
                  },
                  "caat": {
                    "type": "string",
                    "format": "binary"
                  },
                  "insurancePolicy": {
                    "type": "string",
                    "format": "binary"
                  },
                  "oea": {
                    "type": "string",
                    "format": "binary"
                  },
                  "ctpat": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_usa_w9_Form": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_usa_utility_Bill": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_copia_Rfc_Form": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_constance_Of_Fiscal_Situation": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_proof_of_Favorable": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_proof_Of_Address": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": ["Manage Carrier"],
        "summary": "Get All",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "keyWord",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "Test"
          },
          {
            "name": "sortBy",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "blocked , recent , all"
          },
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "1"
          },
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "10"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/module/carrier/{carrierAccountId}": {
      "get": {
        "tags": ["Manage Carrier"],
        "summary": "Get Details",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["Manage Carrier"],
        "summary": "Update",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "companyName": {
                    "type": "string",
                    "example": "Example Logistics Inc."
                  },
                  "contactName": {
                    "type": "string",
                    "example": "John Doe"
                  },
                  "countryCode": {
                    "type": "integer",
                    "example": "1"
                  },
                  "contactNumber": {
                    "type": "string",
                    "example": "1234567890"
                  },
                  "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "Password123"
                  },
                  "commercialReference[0][companyName]": {
                    "type": "string",
                    "example": "Commercial Partner 1"
                  },
                  "commercialReference[0][contactName]": {
                    "type": "string",
                    "example": "Jane Smith"
                  },
                  "commercialReference[0][emailAddress]": {
                    "type": "string",
                    "example": "jane.smith@partner1.com"
                  },
                  "commercialReference[0][countryCode]": {
                    "type": "integer",
                    "example": "1"
                  },
                  "commercialReference[0][contactNo]": {
                    "type": "integer",
                    "example": "9876543210"
                  },
                  "commercialReference[1][companyName]": {
                    "type": "string",
                    "example": "Commercial Partner 2"
                  },
                  "commercialReference[1][contactName]": {
                    "type": "string",
                    "example": "James Brown"
                  },
                  "commercialReference[1][emailAddress]": {
                    "type": "string",
                    "example": "james.brown@partner2.com"
                  },
                  "commercialReference[1][countryCode]": {
                    "type": "integer",
                    "example": "44"
                  },
                  "commercialReference[1][contactNo]": {
                    "type": "integer",
                    "example": "447123456789"
                  },
                  "companyFormationType": {
                    "type": "string",
                    "example": "USA"
                  },
                  "profilePicture": {
                    "type": "string",
                    "format": "binary"
                  },
                  "scac": {
                    "type": "string",
                    "format": "binary"
                  },
                  "caat": {
                    "type": "string",
                    "format": "binary"
                  },
                  "insurancePolicy": {
                    "type": "string",
                    "format": "binary"
                  },
                  "oea": {
                    "type": "string",
                    "format": "binary"
                  },
                  "ctpat": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_usa_w9_Form": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_usa_utility_Bill": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_copia_Rfc_Form": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_constance_Of_Fiscal_Situation": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_proof_of_Favorable": {
                    "type": "string",
                    "format": "binary"
                  },
                  "companyFormation_maxico_proof_Of_Address": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiVTJGc2RHVmtYMTgrWHQxL05iUDRoVGprWlFiVVlsOHBvM2Z6U1BjajV4N09HdzFkQUdHZXlJRVZUTXdLMGNYeSIsInR5cGUiOiJBY2Nlc3MiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3MjQ5MzU0MTQsImV4cCI6MTcyNTAyMTgxNH0.BpphBKiGwrY-_f4rmi-r31B-axEDpK-78DB9j9sagg4"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": ["Manage Carrier"],
        "summary": "Delete",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/module/verify/carrier/{carrierAccountId}": {
      "post": {
        "tags": ["Manage Carrier"],
        "summary": "Verify",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": ""
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/module/unverify/carrier/{carrierAccountId}": {
      "delete": {
        "tags": ["Manage Carrier"],
        "summary": "Unverify",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/services/": {
      "get": {
        "tags": ["Service"],
        "summary": "Fetch Movement",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "1"
          },
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "10"
          },
          {
            "name": "keyWord",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "MYWYBVRRRV4328325499"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/services/{movementId}": {
      "get": {
        "tags": ["Service"],
        "summary": "Get Details",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["Service"],
        "summary": "Hendle Request",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "carrierId": "66c5aa038c1687ae1adc0c22",
                  "operatorId": "66c49148789b754e236b13ac",
                  "vehicleId": "66c7187e839c733bfb28ace2"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/operator/": {
      "post": {
        "tags": ["Operator"],
        "summary": "Create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "carrierId": "66d1ab55fd174dd1db7c9737",
                  "operatorName": "john doe",
                  "operatorNumber": 9876543212,
                  "mxIdBadge": "MX12345",
                  "mxIdBadgeExpirationDate": "2025-12-31",
                  "fastId": "FAST67890",
                  "fastIdExpirationDate": "2026-05-30",
                  "mxDriversLicense": "MXDL98765",
                  "mxDriversLicenseExpirationDate": "2027-10-15",
                  "usDriversLicense": "USDL54321",
                  "usDriversLicenseExpirationDate": "2028-03-22"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/operator/fetch/{carrierAccountId}": {
      "get": {
        "tags": ["Operator"],
        "summary": "Fetch Data",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "keyWord",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "1"
          },
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "10"
          },
          {
            "name": "sortBy",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "recent"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/operator/{operatorAccountId}": {
      "get": {
        "tags": ["Operator"],
        "summary": "Get Details",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["Operator"],
        "summary": "Update",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "operatorName": "john doe22",
                  "operatorNumber": 9876543210,
                  "mxIdBadge": "MX12345",
                  "mxIdBadgeExpirationDate": "2025-12-31",
                  "fastId": "FAST67890",
                  "fastIdExpirationDate": "2026-05-30",
                  "mxDriversLicense": "MXDL98765",
                  "mxDriversLicenseExpirationDate": "2027-10-15",
                  "usDriversLicense": "USDL54321",
                  "usDriversLicenseExpirationDate": "2028-03-22"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": ["Operator"],
        "summary": "Delete",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/vehicle/": {
      "post": {
        "tags": ["Vehicle"],
        "summary": "Create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "carrierId": "{carrierAccountId}",
                  "vehicleName": "truck123",
                  "mxPlates": "MX-ABC-1234",
                  "mxPlatesExpirationDate": "2025-01-01",
                  "usPlates": "US-DEF-5678",
                  "usPlatesExpirationDate": "2025-02-01",
                  "mxInsurancePlates": "MX-INS-9101",
                  "mxInsurancePlatesExpirationDate": "2025-03-01",
                  "usInsurancePlates": "US-INS-1121",
                  "usInsurancePlatesExpirationDate": "2025-04-01",
                  "typeOfService": [
                    {
                      "title": "Express Delivery",
                      "description": "Fast delivery service within 24 hours."
                    },
                    {
                      "title": "Standard Delivery",
                      "description": "Regular delivery service within 3-5 business days."
                    }
                  ],
                  "typeOfTransportation": [
                    {
                      "title": "Refrigerated",
                      "description": "Transport of perishable goods."
                    },
                    {
                      "title": "Dry Goods",
                      "description": "Transport of non-perishable goods."
                    }
                  ],
                  "modeOfTransportation": {
                    "FTL": [
                      {
                        "title": "Full Truckload",
                        "description": "Dedicated truck for one shipment."
                      }
                    ],
                    "LTL": [
                      {
                        "title": "Less Than Truckload",
                        "description": "Shared truck for multiple shipments."
                      }
                    ]
                  },
                  "status": "Active"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/vehicle/fetch/{carrierAccountId}": {
      "get": {
        "tags": ["Vehicle"],
        "summary": "Fetch Data",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "keyWord",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "1"
          },
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "10"
          },
          {
            "name": "sortBy",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "recent"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/vehicle/{vehicleId}": {
      "get": {
        "tags": ["Vehicle"],
        "summary": "Get Details",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["Vehicle"],
        "summary": "Update",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "vehicleName": "truck123456789",
                  "mxPlates": "MX-ABC-1234",
                  "mxPlatesExpirationDate": "2025-01-01",
                  "usPlates": "US-DEF-5678",
                  "usPlatesExpirationDate": "2025-02-01",
                  "mxInsurancePlates": "MX-INS-9101",
                  "mxInsurancePlatesExpirationDate": "2025-03-01",
                  "usInsurancePlates": "US-INS-1121",
                  "usInsurancePlatesExpirationDate": "2025-04-01",
                  "typeOfService": [
                    {
                      "title": "Express Delivery",
                      "description": "Fast delivery service within 24 hours."
                    },
                    {
                      "title": "Standard Delivery",
                      "description": "Regular delivery service within 3-5 business days."
                    }
                  ],
                  "typeOfTransportation": [
                    {
                      "title": "Refrigerated",
                      "description": "Transport of perishable goods."
                    },
                    {
                      "title": "Dry Goods",
                      "description": "Transport of non-perishable goods."
                    }
                  ],
                  "modeOfTransportation": {
                    "FTL": [
                      {
                        "title": "Full Truckload",
                        "description": "Dedicated truck for one shipment."
                      }
                    ],
                    "LTL": [
                      {
                        "title": "Less Than Truckload",
                        "description": "Shared truck for multiple shipments."
                      }
                    ]
                  },
                  "status": "Active"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": ["Vehicle"],
        "summary": "Delete",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/activity/user": {
      "get": {
        "tags": ["Activity"],
        "summary": "User Activity",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "startDate",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "2024-09-01"
          },
          {
            "name": "endDate",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "2024-09-03"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/activity/carrier": {
      "get": {
        "tags": ["Activity"],
        "summary": "Carrier Activity",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "startDate",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "2024-09-01"
          },
          {
            "name": "endDate",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "2024-09-03"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/activity/service": {
      "get": {
        "tags": ["Activity"],
        "summary": "Service Activity",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "startDate",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "2024-09-01"
          },
          {
            "name": "endDate",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "2024-09-03"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/banners": {
      "post": {
        "tags": ["Banners"],
        "summary": "Upload Banners",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "user_mainBanner": {
                    "type": "string",
                    "format": "binary"
                  },
                  "user_serviceBanner": {
                    "type": "string",
                    "format": "binary"
                  },
                  "user_operationsBanner": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": ["Banners"],
        "summary": "Fetch Banners",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/admin/transitInfo": {
      "post": {
        "tags": ["TransitInfo"],
        "summary": "Add TransitInfo",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "typeOfService": [
                    {
                      "title": "Northbound",
                      "description": "Lorem ipsum dolor sit amet Mauris risus turpis."
                    },
                    {
                      "title": "Southbound",
                      "description": "Lorem ipsum dolor sit amet Mauris risus turpis."
                    },
                    {
                      "title": "Local Drayage MX",
                      "description": "Lorem ipsum dolor sit amet Mauris risus turpis."
                    },
                    {
                      "title": "Local Drayage US",
                      "description": "Lorem ipsum dolor sit amet Mauris risus turpis."
                    }
                  ],
                  "typeOfTransportation": [
                    {
                      "title": "FTL",
                      "description": "Lorem ipsum dolor sit amet Mauris risus turpis."
                    },
                    {
                      "title": "LTL",
                      "description": "Lorem ipsum dolor sit amet Mauris risus turpis."
                    }
                  ],
                  "modeOfTransportation": {
                    "FTL": [
                      {
                        "title": "Dry Box",
                        "description": "Lorem ipsum dolor sit amet Mauris risus turpis."
                      },
                      {
                        "title": "Reefer",
                        "description": "Lorem ipsum dolor sit amet Mauris risus turpis."
                      },
                      {
                        "title": "Flatbed",
                        "description": "Lorem ipsum dolor sit amet Mauris risus turpis."
                      },
                      {
                        "title": "Lowboy",
                        "description": "Lorem ipsum dolor sit amet Mauris risus turpis."
                      },
                      {
                        "title": "Semi-Lowbo",
                        "description": "Lorem ipsum dolor sit amet Mauris risus turpis."
                      }
                    ],
                    "LTL": [
                      {
                        "title": "Pickup",
                        "description": "Max weight: 12TON"
                      },
                      {
                        "title": "One Ton / 4 PLT",
                        "description": "Lorem ipsum dolor sit amet consectetur, Mauris risus turpis."
                      },
                      {
                        "title": "12 Footer",
                        "description": "Lorem ipsum dolor sit amet consecteturr Mauris risus turpis."
                      },
                      {
                        "title": "16 Footer",
                        "description": "Lorem ipsum dolor sit amet consecteturr Mauris risus turpis."
                      },
                      {
                        "title": "18 Footer",
                        "description": "Lorem ipsum dolor sit amet consecteturr Mauris risus turpis."
                      },
                      {
                        "title": "20 Footer",
                        "description": "Lorem ipsum dolor sit amet consecteturr Mauris risus turpis."
                      },
                      {
                        "title": "Bobtail 22 footer",
                        "description": "Lorem ipsum dolor sit amet consecteturr Mauris risus turpis."
                      },
                      {
                        "title": "Bobtail 26 footer",
                        "description": "Lorem ipsum dolor sit amet consecteturr Mauris risus turpis."
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": ["TransitInfo"],
        "summary": "Fetch TransitInfo",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },

    "/v1/common/otp/sent/admin": {
      "post": {
        "tags": ["Otp"],
        "summary": "Sent Otp",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "admin@gmail.com"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/common/otp/verify": {
      "post": {
        "tags": ["Otp"],
        "summary": "Verify Otp",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "admin@gmail.com",
                  "otp": 527617
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/common/resetPassword/admin": {
      "post": {
        "tags": ["Forgot Password"],
        "summary": "Reset Password",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "admin@gmail.com",
                  "password": "P@ssw0rd123",
                  "otpToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcyMzc5NzU1MSwiZXhwIjoxNzIzNzk3ODUxfQ.k0lGZ5Z2iQeJBoog3FKVqT1SmwXTeh_3TMUtkA33Bpc"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    }
  }
}
