{
  "openapi": "3.1.0",
  "info": {
    "title": "CargoConnect Carrier API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:5555",
      "description": "Local server"
    },
    {
      "url": "https://cargo-connect-be.vercel.app",
      "description": "Live server"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "tags": [
    {
      "name": "---- Carrier ----"
    },
    {
      "name": "Auth"
    },
    {
      "name": "Profile"
    },
    {
      "name": "Movement"
    },
    {
      "name": "Operator"
    },
    {
      "name": "Vehicle"
    },
    {
      "name": "---- Common ----"
    },
    {
      "name": "Otp"
    },
    {
      "name": "Forgot Password"
    },
    {
      "name": "Image Upload"
    }
  ],
  "paths": {
    "/v1/carrier/auth/signUp": {
      "post": {
        "tags": ["Auth"],
        "summary": "Sign Up",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "profilePicture": "https://example.com/path/to/profile-picture.jpg",
                  "companyName": "Example Logistics Inc.",
                  "contactName": "John Doe",
                  "contactNumber": 1234567890,
                  "email": "johndoe@example.com",
                  "password": "securePassword123",
                  "scac": "https://example.com/path/to/profile-picture.jpg",
                  "caat": "https://example.com/path/to/profile-picture.jpg",
                  "insurancePolicy": "https://example.com/path/to/profile-picture.jpg",
                  "oea": "https://example.com/path/to/profile-picture.jpg",
                  "ctpat": "https://example.com/path/to/profile-picture.jpg",
                  "companyFormation": {
                    "usa": {
                      "w9_Form": "https://example.com/path/to/w9-form.pdf",
                      "utility_Bill": "https://example.com/path/to/utility-bill.pdf"
                    }
                  },
                  "commercialReference": [
                    {
                      "companyName": "Commercial Partner 1",
                      "contactName": "Jane Smith",
                      "emailAddress": "jane.smith@partner1.com",
                      "countryCode": 1,
                      "contactNo": 9876543210
                    },
                    {
                      "companyName": "Commercial Partner 2",
                      "contactName": "James Brown",
                      "emailAddress": "james.brown@partner2.com",
                      "countryCode": 44,
                      "contactNo": 447123456789
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/carrier/auth/logIn": {
      "post": {
        "tags": ["Auth"],
        "summary": "Log In",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "john.doe@example.com",
                  "password": "P@ssw0rd123"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/carrier/auth/logOut": {
      "post": {
        "tags": ["Auth"],
        "summary": "Log Out",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": ""
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/carrier/profile": {
      "get": {
        "tags": ["Profile"],
        "summary": "Profile",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["Profile"],
        "summary": "update",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "companyName": "example company",
                  "contactName": "john doe",
                  "contactNumber": 1234567890,
                  "email": "john.doe@example.com",
                  "scac": null,
                  "insurancePolicy": null,
                  "oea": null,
                  "ctpat": null,
                  "companyFormation": {
                    "usa": {
                      "w9_Form": "http://example.com/w9_form.pdf",
                      "utility_Bill": "http://example.com/utility_bill.pdf"
                    }
                  },
                  "commercialReference": [
                    {
                      "companyName": "reference company 1",
                      "contactName": "reference contact 1",
                      "emailAddress": "reference1@example.com",
                      "countryCode": 1,
                      "contactNo": 9876543210,
                      "_id": "66bf2f403cfdbfd964a1280b"
                    },
                    {
                      "companyName": "reference company 2",
                      "contactName": "reference contact 2",
                      "emailAddress": "reference2@example.com",
                      "countryCode": 1,
                      "contactNo": 1234567890,
                      "_id": "66bf2f403cfdbfd964a1280c"
                    }
                  ],
                  "verifyByAdmin": false,
                  "isBlocked": false,
                  "lastLogin": "2024-08-16T10:52:01.469Z",
                  "createdAt": "2024-08-16T10:51:44.087Z",
                  "updatedAt": "2024-08-16T10:52:01.480Z"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/carrier/movement": {
      "get": {
        "tags": ["Movement"],
        "summary": "Fetch Movement",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "1"
          },
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "10"
          },
          {
            "name": "sortBy",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "Completed"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/carrier/movement/{movementId}": {
      "get": {
        "tags": ["Movement"],
        "summary": "Get Details",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["Movement"],
        "summary": "Hendle Request",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "operatorId": "66c49148789b754e236b13ac",
                  "vehicleId": "66c7187e839c733bfb28ace2"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/carrier/operator/": {
      "post": {
        "tags": ["Operator"],
        "summary": "Create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "operatorName": "john doe",
                  "operatorNumber": 9876543210,
                  "mxIdBadge": "MX12345",
                  "mxIdBadgeExpirationDate": "2025-12-31",
                  "fastId": "FAST67890",
                  "fastIdExpirationDate": "2026-05-30",
                  "mxDriversLicense": "MXDL98765",
                  "mxDriversLicenseExpirationDate": "2027-10-15",
                  "usDriversLicense": "USDL54321",
                  "usDriversLicenseExpirationDate": "2028-03-22"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/carrier/operator": {
      "get": {
        "tags": ["Operator"],
        "summary": "Fetch Data",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "keyWord",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "1"
          },
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "10"
          },
          {
            "name": "sortBy",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "recent"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/carrier/operator/{operatorId}": {
      "get": {
        "tags": ["Operator"],
        "summary": "Get Details",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["Operator"],
        "summary": "Update",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "operatorName": "john doe22",
                  "operatorNumber": 9876543210,
                  "mxIdBadge": "MX12345",
                  "mxIdBadgeExpirationDate": "2025-12-31",
                  "fastId": "FAST67890",
                  "fastIdExpirationDate": "2026-05-30",
                  "mxDriversLicense": "MXDL98765",
                  "mxDriversLicenseExpirationDate": "2027-10-15",
                  "usDriversLicense": "USDL54321",
                  "usDriversLicenseExpirationDate": "2028-03-22"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": ["Operator"],
        "summary": "Delete",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/carrier/vehicle/": {
      "post": {
        "tags": ["Vehicle"],
        "summary": "Create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "vehicleName": "truck123",
                  "mxPlates": "MX-ABC-1234",
                  "mxPlatesExpirationDate": "2025-01-01",
                  "usPlates": "US-DEF-5678",
                  "usPlatesExpirationDate": "2025-02-01",
                  "mxInsurancePlates": "MX-INS-9101",
                  "mxInsurancePlatesExpirationDate": "2025-03-01",
                  "usInsurancePlates": "US-INS-1121",
                  "usInsurancePlatesExpirationDate": "2025-04-01",
                  "typeOfService": [
                    {
                      "title": "Express Delivery",
                      "description": "Fast delivery service within 24 hours."
                    },
                    {
                      "title": "Standard Delivery",
                      "description": "Regular delivery service within 3-5 business days."
                    }
                  ],
                  "typeOfTransportation": [
                    {
                      "title": "Refrigerated",
                      "description": "Transport of perishable goods."
                    },
                    {
                      "title": "Dry Goods",
                      "description": "Transport of non-perishable goods."
                    }
                  ],
                  "modeOfTransportation": {
                    "FTL": [
                      {
                        "title": "Full Truckload",
                        "description": "Dedicated truck for one shipment."
                      }
                    ],
                    "LTL": [
                      {
                        "title": "Less Than Truckload",
                        "description": "Shared truck for multiple shipments."
                      }
                    ]
                  },
                  "status": "Active"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/carrier/vehicle": {
      "get": {
        "tags": ["Vehicle"],
        "summary": "Fetch Data",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "keyWord",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "1"
          },
          {
            "name": "limit",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "10"
          },
          {
            "name": "sortBy",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "recent"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/carrier/vehicle/{vehicleId}": {
      "get": {
        "tags": ["Vehicle"],
        "summary": "Get Details",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": ["Vehicle"],
        "summary": "Update",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "vehicleName": "truck123456789",
                  "mxPlates": "MX-ABC-1234",
                  "mxPlatesExpirationDate": "2025-01-01",
                  "usPlates": "US-DEF-5678",
                  "usPlatesExpirationDate": "2025-02-01",
                  "mxInsurancePlates": "MX-INS-9101",
                  "mxInsurancePlatesExpirationDate": "2025-03-01",
                  "usInsurancePlates": "US-INS-1121",
                  "usInsurancePlatesExpirationDate": "2025-04-01",
                  "typeOfService": [
                    {
                      "title": "Express Delivery",
                      "description": "Fast delivery service within 24 hours."
                    },
                    {
                      "title": "Standard Delivery",
                      "description": "Regular delivery service within 3-5 business days."
                    }
                  ],
                  "typeOfTransportation": [
                    {
                      "title": "Refrigerated",
                      "description": "Transport of perishable goods."
                    },
                    {
                      "title": "Dry Goods",
                      "description": "Transport of non-perishable goods."
                    }
                  ],
                  "modeOfTransportation": {
                    "FTL": [
                      {
                        "title": "Full Truckload",
                        "description": "Dedicated truck for one shipment."
                      }
                    ],
                    "LTL": [
                      {
                        "title": "Less Than Truckload",
                        "description": "Shared truck for multiple shipments."
                      }
                    ]
                  },
                  "status": "Active"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": ["Vehicle"],
        "summary": "Delete",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/common/otp/sent/admin": {
      "post": {
        "tags": ["Otp"],
        "summary": "Sent Otp",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "admin@gmail.com"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/common/otp/verify": {
      "post": {
        "tags": ["Otp"],
        "summary": "Verify Otp",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "admin@gmail.com",
                  "otp": 527617
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/common/resetPassword/admin": {
      "post": {
        "tags": ["Forgot Password"],
        "summary": "Reset Password",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "admin@gmail.com",
                  "password": "P@ssw0rd123",
                  "otpToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcyMzc5NzU1MSwiZXhwIjoxNzIzNzk3ODUxfQ.k0lGZ5Z2iQeJBoog3FKVqT1SmwXTeh_3TMUtkA33Bpc"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/v1/common/imageUpload": {
      "post": {
        "tags": ["Image Upload"],
        "summary": "imageUpload",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    }
  }
}
